services:
  # NOTIFICATION MICROSERVICE
  # --------------------------------------------------------------
  notification-service:
    container_name: notification-service
    image: safaalaloosi/notification-service:f5732b784ccb6af4bbfab02ccee5adc90849f287
    #build: ./notification-service
    ports:
      - "8070:8080"
    depends_on:
      - notification-service-postgres
      - rabbitmq

  notification-service-postgres:
    container_name: notificatoin-service-db
    image: postgres:latest
    ports:
      - "5430:5432"
    volumes:
      - "./docker-volumes/notification-postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"


  # REQUEST MICROSERVICE
  # --------------------------------------------------------------
  request-service:
    container_name: request-service
    image: safaalaloosi/request-service:latest
    #build: ./request-service
    ports:
      - "8071:8080"
    depends_on:
      - request-service-postgres
      - rabbitmq

  request-service-postgres:
    container_name: request-service-db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "./docker-volumes/req-postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
   
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./docker-volumes/rabbitmq/data/:/var/lib/rabbitmq/"
      - "./docker-volumes/rabbitmq/log/:/var/log/rabbitmq"

  
  # SERVICE-DISPATCHER MICROSERVICE
  # --------------------------------------------------------------
  service-dispatcher-service:
    container_name: service-dispatcher-service
    image: safaalaloosi/service-provider-dispatcher-service:f5732b784ccb6af4bbfab02ccee5adc90849f287
    #build: ./service-provider-dispatcher-service
    ports:
      - "8072:8080"
    depends_on:
      - service-dispatcher-postgres
      - rabbitmq

  service-dispatcher-postgres:
    container_name: service-dispatcher-db
    image: postgres:latest
    ports:
      - "5431:5432"
    volumes:
      - "./docker-volumes/sd-postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"


  # COMMON SERVICES
  # --------------------------------------------------------------
  postgres_admin_portal:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:5050"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@gmail.com"
      - "PGADMIN_DEFAULT_PASSWORD=admin"
      - "PGADMIN_LISTEN_PORT=5050"