name: Build Notificatoin Service

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./notification-service
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./notification-service
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./notification-service

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{secrets.SAFA_DH_USERNAME}}
        password: ${{secrets.SAFA_DH_PASSWORD}}
        logout: true

    - name: Build & Push Docker Image
      env:
        IMAGE_TAG: ${{github.sha}}
      run: |
        docker build -t docker.io/${{secrets.SAFA_DH_USERNAME}}/notification-service:${IMAGE_TAG} ./notification-service/
        docker push docker.io/${{secrets.SAFA_DH_USERNAME}}/notification-service:${IMAGE_TAG}
