name: Build Request Service

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker-container # Use the docker-container driver for multi-platform builds

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./request-service
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./request-service
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./request-service

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{secrets.SAFA_DH_USERNAME}}
        password: ${{secrets.SAFA_DH_PASSWORD}}
        logout: true

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./request-service/ # Path to the Docker build context
        platforms: linux/amd64,linux/arm64 # Target platforms
        push: true # Push the image to Docker Hub
        tags: |
          docker.io/${{ secrets.SAFA_DH_USERNAME }}/request-service:${{ github.sha }}
          docker.io/${{ secrets.SAFA_DH_USERNAME }}/request-service:latest
